word = input()
new_word = word.replace("c=", 'a')
new_word = new_word.replace("c-", 'a')
new_word = new_word.replace("dz=", 'a')
new_word = new_word.replace("d-", 'a')
new_word = new_word.replace("lj", 'a')
new_word = new_word.replace("nj", 'a')
new_word = new_word.replace("s=", 'a')
new_word = new_word.replace("z=", 'a')
print(len(new_word))